apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: staged-workflow-sample

permissions:
  scm-token-org: read

on:
  push:
    branches:
      - '**'
  workflow_dispatch: {}

jobs:
  job-A:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout/.cloudbees/testing@main
        with:
          # ssh-key: ${{ secrets.ssh2 }}
          repository: git@github.com:cb-nsrinivasa/ssh-check.git

      - name: Show .git/config
        uses: docker://alpine:3.20
        run: |
          cat /cloudbees/workspace/.git/config

      - name: Configure Git Global Credentials
        uses: cloudbees-io/configure-git-global-credentials/.cloudbees/testing@CBP-18304

      - name: Show .gitconfig
        uses: docker://alpine:3.20
        run: |
          cat /cloudbees/home/.gitconfig

      - name: Clone via HTTPS (no .git)
        uses: docker://alpine:3.20
        continue-on-error: true
        run: |
          apk update
          apk add git openssh-client
          git clone https://github.com/cb-nsrinivasa/configure-git-credentials-v2-testing

      - name: Clone via HTTPS (.git)
        uses: docker://alpine:3.20
        continue-on-error: true
        run: |
          apk update
          apk add git openssh-client
          git clone https://github.com/cb-nsrinivasa/configure-git-credentials-v2-testing.git

      - name: Clone via HTTP (no .git)
        uses: docker://alpine:3.20
        continue-on-error: true
        run: |
          apk update
          apk add git openssh-client
          [ -d "configure-git-credentials-v2-testing" ] && rm -rf "configure-git-credentials-v2-testing"
          git clone http://github.com/cb-nsrinivasa/configure-git-credentials-v2-testing

      - name: Clone via HTTP (.git)
        uses: docker://alpine:3.20
        continue-on-error: true
        run: |
          apk update
          apk add git openssh-client
          [ -d "configure-git-credentials-v2-testing" ] && rm -rf "configure-git-credentials-v2-testing"
          git clone http://github.com/cb-nsrinivasa/configure-git-credentials-v2-testing.git
